[package]
name = "terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.0"
regex = "1.11.1"
chrono = { version = "0.4.40", features = ["serde"] }
sqlx = { version = "0.8.3", features = ["bigdecimal", "chrono", "postgres", "runtime-tokio", "uuid"] }
app = { path = "../app"}

